# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: KJuicer
email: info@kjuicer.com
description: > # this means to ignore newlines until "baseurl:"
  Reading gets super powers
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.kjuicer.com" # the base hostname & protocol for your site
twitter_username: KnowledgeJuicer
github_username:  kjuicer
youtube_channel: UCleRhrYoSl9DbeU6GZu_DTQ
facebook_page: kjuicer
assets: /post_assets/

# Build settings
markdown: kramdown
