# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: KJuicer
description: > # this means to ignore newlines until "baseurl:"
  Reading gets super powers
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.kjuicer.com" # the base hostname & protocol for your site
twitter_username: KnowledgeJuicer
github_username:  kjuicer
youtube_channel: UCleRhrYoSl9DbeU6GZu_DTQ
facebook_page: kjuicer
assets: /post_assets/

sass:
  sass_dir: _sass
  style: compressed

# Build settings
markdown: kramdown
home:
  en: /
  it: /it/
t:
  en:
    copyright: "© 2016 KJuicer.com, All rights reserved."
    keep_in_touch: "Keep in touch"
    links: "Links"
    published: "Published on"
    switch: "Switch to English"
  it:
    copyright: "© 2016 KJuicer.com, Tutti i diritti sono riservati."
    keep_in_touch: "Resta in contatto"
    links: "Collegamenti"
    published: "Pubblicato il"
    switch: "Visualizza in Italiano"

footer_menu:
  en:
#  - label: Support
#    href: /support
  - label: Legal
    href: /legal
  - label: Privacy Policy
    href: /privacy-policy
#  - label: Cookie Policy
#    href: /cookie-policy
  it:
#  - label: Supporto
#    href: /it/support
  - label: Informazioni legali
    href: /it/legal
  - label: Privacy Policy
    href: /it/privacy-policy
  - label: Cookie Policy
    href: /it/cookie-policy

header_menu:
  en:
  - label: Blog
    href: /blog
  - label: Presentation
    href: /presentation
  - label: About
    href: /about
  it:
  - label: Blog
    href: /it/blog
  - label: Presentazione
    href: /it/presentation
  - label: About
    href: /it/about

call_to_action:
  en:
    label: Try KJuicer
    href: http://alpha.kjuicer.com/cache/484/demo/
  it:
    label: Prova KJuicer
    href: http://alpha.kjuicer.com/cache/4549/demo/
